### ISSUE TITLE
IsChanged/IsChangedLocal returns true with no real property changes

### ISSUE THREAD

**Issue by japaol** [docevaad/Anchor#39]
If a property changes its value, and changes again to the previous value, `IsChanged` and `IsChangedLocal` both returns `true` when it should be `false`. In that case, `ChangedProperties` returns an empty collection of properties, which is correct.

**Comment by Grauenwolf** [comment]
It's unlikely that we can support this scenario. 

Right now it's just a trip flag, we don't track what's changed. Undoing it would require rechecking all of the other properties to see if anything else has changed. 

Now I won't close this right away because we may be able to support a change counter, allowing us to only recheck the one field. But I can't promise it will work.

**Comment by Grauenwolf** [comment]
Work plan:

1. Add an `PropertyIndex` property to the `PropertyMetadata` class
2. Replace the dictionaries we use to back properties with arrays.
3. Populate the dictionaries with `NotSet.Value`. (A null would mean an actual null.)
4. Add a `BitArray` to track which fields have been modified.
5. When calling `Set`, perform a comparison between the new and original value. This will be used to update the `BitArray`. 
6. New logic:

    if bitArray[propertyIndex] was 1 and is now 0 then 
        if all other bits are 0 then
            change m_IsChangedLocal to false

Prediction:

The cost savings from not using a dictionary to store values (memory, hashing time) will compensate for the cost of managing the bitfield and the extra comparison check.

Timeline:

Lets plan this for v3.2. We've already got enough featured in v3.1.

**Comment by Grauenwolf** [comment]
The re-write is done and all existing tests are passing.

I still need to write new tests for this actual scenario, but it looks promising.

**Comment by Grauenwolf** [comment]
ChangeTrackingModelBase and EditableObjectModelBase tests pass.

ChangeTrackingModelCollection does not pass. Need to account for collections.
